version: '3.0'

services:
  grafana:
    container_name: 'grafana-windrose-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
    environment:
      GF_INSTALL_PLUGINS: "https://github.com/VictoriaMetrics/grafana-datasource/releases/download/v0.10.3/victoriametrics-datasource-v0.10.3.zip;victoriametrics-datasource"
      GF_PLUGINS_ENABLE_ALPHA: "true"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victoriametrics-datasource"
    ports:
      - 3001:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-windrose-panel
      - ./provisioning:/etc/grafana/provisioning
